from __future__ import annotations
from abc import ABC, abstractmethod
from uuid import UUID
from app.schemas.ui import ConversationSession, ConversationMessage
class ConversationRepository(ABC):
    @abstractmethod
    def create_session(self, session: ConversationSession)->ConversationSession: ...
    @abstractmethod
    def get_session(self, session_id: UUID)->ConversationSession|None: ...
    @abstractmethod
    def add_message(self, message: ConversationMessage)->ConversationMessage: ...
    @abstractmethod
    def get_messages(self, session_id: UUID)->list[ConversationMessage]: ...
    @abstractmethod
    def clear_session(self, session_id: UUID)->None: ...
